server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: bunny

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      password:

  cache:
    type: simple

jwt:
  secret: my-secret-key-jwt-secret-key-example-delivery
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
